site_name: UBM Documentation
site_url: https://ubm-driverless.github.io/ubm-docs/

# WARNING: do not change the default value of docs_dir. Otherwise, private repositories will be exposed!
#
# docs_dir: docs
#

nav:
  - Setup: setup/
  - Guides: guides/
  - Python Packages: PYTHON_PACKAGES/index.md
  - C++ Packages: CPP_PACKAGES/

# To set up another entry in the navigation: 
# - NAME_OF_THE_SECTION: FOLDER_NAME_INSIDE_DOCS/

  

# File/Folders to not include in mkdocs build process
draft_docs: |
  /rosdoc2_generated/

theme:
  logo: assets/UBM-Logo.png
  favicon: assets/favicon.png
  name: material
  features:
    - navigation.tabs
    - navigation.prune
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      primary: indigo
      accent: red
      text: '#ececec'
      background: '#212121'
      
  
plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
          python:
            options:
              show_source: false # WARNING: do not change this value. Otherwise, private repositories will be exposed!

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: '2024 © UniBo Motorsport'

extra:
  generator: false
  version:
    provider: mike

repo_url: https://github.com/ubm-driverless
repo_name: ubm-driverless
