site_name: UBM Documentation
site_url: https://ubm-driverless.github.io/ubm-docs/

# WARNING: do not change the default value of docs_dir. Otherwise, private repositories will be exposed!
#
# docs_dir: docs
#

draft_docs: |
  /cpp_packages/
  /python_packages/

theme:
  logo: assets/UBM-Logo.png
  favicon: assets/favicon.png
  name: material
  features:
    # - navigation.tabs
    # - navigation.sections
    # - navigation.expand
    - navigation.top
    - toc.follow
    # - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  # font:
  #   text: Roboto
  #   code: Roboto Mono
  palette:
    - scheme: slate
      primary: indigo
      accent: red
  
plugins:
  - search
  - mkdocstrings
  #- offline

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: '2024 © UniBo Motorsport'

extra:
  generator: false
  version:
    provider: mike

repo_url: https://github.com/ubm-driverless
repo_name: ubm-driverless
